# Introduction 

There are two key ideas in this Dissertation. The Application of Multivariate Analysis techniques to Business Analytics and the empowerment of Analysts to build and publish their own Analytics Software Tools. To weave both themes together, I use an illustrative Business Problem. 

My illustrative problem is to develop an Analytics Tool that accurately predicts a Property's Value. There are some very bad property price estimation tools in commercial use. I have documented one such tool in a Case-study at the end of the text. In subsequent chapters I aim to demonstrate that a high performance Analytical tool integrating Statistical and SOftware Elements is easily obtained.

## Document Structure

This document is organised with a linear flow that mirrors the Structure of an Analytics Project. After a Theory Section providing a summarised introduction to Multivariate Analysis, Data Analysis is performed. Subsequently a model is selected to describe the features in the data. Finally a software tool is published containing the model selected.

[MATHEMATICAL THEORY](#Theory)

The Mathematical Theory section starts by establishing the key theoretical concepts required to understand Multivariate Models. The Key Elements Section defines a Random Sample and presents (without proof) the asymptotic properties of the (multivariate) sample mean and sample covariance matrix. The Linear Predictors Section section defines a Linear Predictor Function and the Mean Squared Error criterion for measuring the accuracy of linear prediction functions.

Subsequently I introduce the analytical properties of four distinct Multivariate Techniques which will be applied in subsequent chapters. Each technique emphasises a different aspect of the sample data. The Classical Linear Regression approach focuses on the sample mean, the Principal Component Analysis approach emphasises the sample covariance matrix, Factor Analysis and Canonical Correlation Analysis is a mixture of both.

[ECONOMIC THEORY](#MassCustomisation)

Here I introduce the concept of Mass Customisation and describe its application to Business Analytics. In general terms, Mass Customisation is about the mass production of customised goods and services. It treats each customer as a separate market and through advanced Technology, each individual order is produced using a customised production set-up. 

[DATA](#Data)

The data section is split in two parts.

[ORIGINAL DATA](#OriginalData)

I am interested in applying multivariate analysis to develop an Analytics tool which predicts property prices. To do this, I sourced  a property data-set from the website @kaggle1. I call this the original data set. 

I start by presenting the original data-set which contains sale prices and property details for 21613 residential property transactions between May 2014 and May 2015 in King County USA (includes Seattle). 

I perform significant exploratory analysis in addition to Multivariate Clustering to detect ouliers, a MANOVA technique for Profiling Segments of Properties and Factor Analysis to investigate "hidden" variables.

[ENRICHED DATA](#EnrichedData)

To discover which variables, not included in the data-set, are known to influence property prices I conducted an online literature search. In the [Literature Search](#Literature) subsection, I detail the results. Potential gaps in the Original Data were identified and I performed a significant data enrichment process. This process is documented in the [Enrichment Process](#EnrichmentProcess) subsection.

Following significant exploratory analysis using Geospatial plots, I use Canonical Correlation Analysis to investigate the degree of overlap between the Enriched and the Original Data set.

[MODEL SELECTION](#ModelSelection)

Model Selection starts with a short literature review of Geospatial models. I then perform a hypothesis test using Linear Regression to determine, given the data set, whether it is worthwhile pursuing sophisticated geospatial models.

This section closes by fitting a Multivariate linear regression model.

[EXAMPLE DATA](#Tool)

This section builds the statistical model identified in the Model Selection chapter into an Interactive Analytics Tool.

[CONCLUSIONS](#Conclusions)

This contains concluding remarks and recommendations for nexts steps.
